### ISSUE TITLE
Unable to join discord server

### ISSUE THREAD

**Issue by hibagus** [up-n-atom/8311#37]
Hi there,

I am sorry if this is not appropriate for reporting issues with the Discord server.

I am looking to join the 8311 discord server through the provided [link](https://discord.com/servers/8311-886329492438671420/).
Upon accepting the invite, it said, "Whoops... Unable to accept invite".

Can you help me take a look into the issues? My discord username is hibagus (bagus#8748). 

Thanks!

**Comment by up-n-atom** [comment]
Your account was auto banned on Nov 5th @ 6:33 PM likely because you didn't answer the "Are you human" question correctly.
